# Generated by Django 4.1.7 on 2023-03-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('nombre_post', models.CharField(max_length=60)),
                ('fecha', models.DateField(auto_now=True)),
                ('contenido', models.CharField(max_length=450)),
            ],
        ),
    ]
